"use client";
import { useRef, useState } from "react";
import Counter from "./Counter";

export default function Home() {
  const [showCounter, setShowCounter] = useState(true);
  const counterRef = useRef(null);
  return (
    <div className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black">
      <main className="flex min-h-screen w-full max-w-3xl flex-col items-center justify-between py-32 px-16 bg-white dark:bg-black sm:items-start">
        <button onClick={() => {
          setShowCounter(current => {
            if (!showCounter) counterRef.current.scrollIntoView({ behavior: "smooth" });
            return !current;
          });
        }}>Toggle Counter</button>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc iaculis, mauris nec elementum faucibus, ligula erat scelerisque lorem, nec tincidunt nisi mi a magna. Vestibulum nec dui vel arcu tincidunt pulvinar quis molestie ante. Cras sodales velit sit amet mauris mattis tincidunt. Donec ut eros vitae nibh faucibus facilisis. Ut finibus risus eu aliquet elementum. Sed eget urna luctus, finibus ligula ac, luctus nibh. Phasellus eu magna arcu. In hac habitasse platea dictumst. Praesent ac volutpat quam. Praesent ut est nunc.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc iaculis, mauris nec elementum faucibus, ligula erat scelerisque lorem, nec tincidunt nisi mi a magna. Vestibulum nec dui vel arcu tincidunt pulvinar quis molestie ante. Cras sodales velit sit amet mauris mattis tincidunt. Donec ut eros vitae nibh faucibus facilisis. Ut finibus risus eu aliquet elementum. Sed eget urna luctus, finibus ligula ac, luctus nibh. Phasellus eu magna arcu. In hac habitasse platea dictumst. Praesent ac volutpat quam. Praesent ut est nunc.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc iaculis, mauris nec elementum faucibus, ligula erat scelerisque lorem, nec tincidunt nisi mi a magna. Vestibulum nec dui vel arcu tincidunt pulvinar quis molestie ante. Cras sodales velit sit amet mauris mattis tincidunt. Donec ut eros vitae nibh faucibus facilisis. Ut finibus risus eu aliquet elementum. Sed eget urna luctus, finibus ligula ac, luctus nibh. Phasellus eu magna arcu. In hac habitasse platea dictumst. Praesent ac volutpat quam. Praesent ut est nunc.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc iaculis, mauris nec elementum faucibus, ligula erat scelerisque lorem, nec tincidunt nisi mi a magna. Vestibulum nec dui vel arcu tincidunt pulvinar quis molestie ante. Cras sodales velit sit amet mauris mattis tincidunt. Donec ut eros vitae nibh faucibus facilisis. Ut finibus risus eu aliquet elementum. Sed eget urna luctus, finibus ligula ac, luctus nibh. Phasellus eu magna arcu. In hac habitasse platea dictumst. Praesent ac volutpat quam. Praesent ut est nunc.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc iaculis, mauris nec elementum faucibus, ligula erat scelerisque lorem, nec tincidunt nisi mi a magna. Vestibulum nec dui vel arcu tincidunt pulvinar quis molestie ante. Cras sodales velit sit amet mauris mattis tincidunt. Donec ut eros vitae nibh faucibus facilisis. Ut finibus risus eu aliquet elementum. Sed eget urna luctus, finibus ligula ac, luctus nibh. Phasellus eu magna arcu. In hac habitasse platea dictumst. Praesent ac volutpat quam. Praesent ut est nunc.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc iaculis, mauris nec elementum faucibus, ligula erat scelerisque lorem, nec tincidunt nisi mi a magna. Vestibulum nec dui vel arcu tincidunt pulvinar quis molestie ante. Cras sodales velit sit amet mauris mattis tincidunt. Donec ut eros vitae nibh faucibus facilisis. Ut finibus risus eu aliquet elementum. Sed eget urna luctus, finibus ligula ac, luctus nibh. Phasellus eu magna arcu. In hac habitasse platea dictumst. Praesent ac volutpat quam. Praesent ut est nunc.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc iaculis, mauris nec elementum faucibus, ligula erat scelerisque lorem, nec tincidunt nisi mi a magna. Vestibulum nec dui vel arcu tincidunt pulvinar quis molestie ante. Cras sodales velit sit amet mauris mattis tincidunt. Donec ut eros vitae nibh faucibus facilisis. Ut finibus risus eu aliquet elementum. Sed eget urna luctus, finibus ligula ac, luctus nibh. Phasellus eu magna arcu. In hac habitasse platea dictumst. Praesent ac volutpat quam. Praesent ut est nunc.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc iaculis, mauris nec elementum faucibus, ligula erat scelerisque lorem, nec tincidunt nisi mi a magna. Vestibulum nec dui vel arcu tincidunt pulvinar quis molestie ante. Cras sodales velit sit amet mauris mattis tincidunt. Donec ut eros vitae nibh faucibus facilisis. Ut finibus risus eu aliquet elementum. Sed eget urna luctus, finibus ligula ac, luctus nibh. Phasellus eu magna arcu. In hac habitasse platea dictumst. Praesent ac volutpat quam. Praesent ut est nunc.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc iaculis, mauris nec elementum faucibus, ligula erat scelerisque lorem, nec tincidunt nisi mi a magna. Vestibulum nec dui vel arcu tincidunt pulvinar quis molestie ante. Cras sodales velit sit amet mauris mattis tincidunt. Donec ut eros vitae nibh faucibus facilisis. Ut finibus risus eu aliquet elementum. Sed eget urna luctus, finibus ligula ac, luctus nibh. Phasellus eu magna arcu. In hac habitasse platea dictumst. Praesent ac volutpat quam. Praesent ut est nunc.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc iaculis, mauris nec elementum faucibus, ligula erat scelerisque lorem, nec tincidunt nisi mi a magna. Vestibulum nec dui vel arcu tincidunt pulvinar quis molestie ante. Cras sodales velit sit amet mauris mattis tincidunt. Donec ut eros vitae nibh faucibus facilisis. Ut finibus risus eu aliquet elementum. Sed eget urna luctus, finibus ligula ac, luctus nibh. Phasellus eu magna arcu. In hac habitasse platea dictumst. Praesent ac volutpat quam. Praesent ut est nunc.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc iaculis, mauris nec elementum faucibus, ligula erat scelerisque lorem, nec tincidunt nisi mi a magna. Vestibulum nec dui vel arcu tincidunt pulvinar quis molestie ante. Cras sodales velit sit amet mauris mattis tincidunt. Donec ut eros vitae nibh faucibus facilisis. Ut finibus risus eu aliquet elementum. Sed eget urna luctus, finibus ligula ac, luctus nibh. Phasellus eu magna arcu. In hac habitasse platea dictumst. Praesent ac volutpat quam. Praesent ut est nunc.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc iaculis, mauris nec elementum faucibus, ligula erat scelerisque lorem, nec tincidunt nisi mi a magna. Vestibulum nec dui vel arcu tincidunt pulvinar quis molestie ante. Cras sodales velit sit amet mauris mattis tincidunt. Donec ut eros vitae nibh faucibus facilisis. Ut finibus risus eu aliquet elementum. Sed eget urna luctus, finibus ligula ac, luctus nibh. Phasellus eu magna arcu. In hac habitasse platea dictumst. Praesent ac volutpat quam. Praesent ut est nunc.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc iaculis, mauris nec elementum faucibus, ligula erat scelerisque lorem, nec tincidunt nisi mi a magna. Vestibulum nec dui vel arcu tincidunt pulvinar quis molestie ante. Cras sodales velit sit amet mauris mattis tincidunt. Donec ut eros vitae nibh faucibus facilisis. Ut finibus risus eu aliquet elementum. Sed eget urna luctus, finibus ligula ac, luctus nibh. Phasellus eu magna arcu. In hac habitasse platea dictumst. Praesent ac volutpat quam. Praesent ut est nunc.</p>
        <div ref={counterRef}> {showCounter && <Counter />}</div>
      </main>
    </div>
  );
}
